TrajectoryPlannerROS:
  max_vel_x: 0.3  #default 0.45
  min_vel_x: 0.05 #default 0.1

 
 # max_vel_y: 0.15
 # min_vel_y: -0.15
  min_vel_theta: 0.1 #default 1.0
  max_vel_theta: 0.7 # not defined in default

  min_in_place_vel_theta: 0.5 # default 0.4
   
  acc_lim_theta: 0.9 # default 3.2
  acc_lim_x: 0.7 # default 2.5
  acc_lim_y: 0.7 # default 2.5

  holonomic_robot: true
  
