
obstacle_range: 2.5 # robot updates its map with information about obstacles within 2.5 meters
raytrace_range: 3.0 # robot attempt to clear out space in front of it up to 3.0 meters
#footprint: [[0.4, 0.3], [-0.4, 0.3], [-0.4,-0.3], [0.4,-0.3]]
footprint: [[0.29,0.19],[-0.29,0.19],[-0.29,-0.19],[0.29,-0.19]]

inflation_radius: 0.36 # robot treats all paths that stay 0.36 meters or more away from obstacles

observation_sources: laser_scan_front laser_scan_rear

laser_scan_front: {sensor_frame: /base_laser_front_link, data_type: LaserScan, topic: /scan_front, marking: true, clearing: true}

laser_scan_rear: {sensor_frame: /base_laser_rear_link, data_type: LaserScan, topic: /scan_rear, marking: true, clearing: true}
