map_type: costmap
robot_base_frame: base_link
obstacle_range: 2.5
raytrace_range: 3.0
observation_sources: laser_scan_front laser_scan_rear
laser_scan_front: {sensor_frame: /base_laser_front_link, data_type: LaserScan, topic: /scan_front, marking: true, clearing: true}
laser_scan_rear: {sensor_frame: /base_laser_rear_link, data_type: LaserScan, topic: /scan_rear, marking: true, clearing: true}
footprint: [[0.29,0.19],[-0.29,0.19],[-0.29,-0.19],[0.29,-0.19]]
