  global_frame: /map
  robot_base_frame: base_footprint 
  update_frequency: 5.0
  publish_frequency: 0.0
  static_map: true # true if map is being provided from map server        
  inflation_radius: 0.36   #default: 0.55

