GlobalPlanner:
    use_grid_path: False # default false
    use_dijkstra: True # default true
    allow_unknown: False # default true
    default_tolerance: 0.2 # default 0.0 
    visualize_potential: True # default false 
    use_quadratic: True # default true
    use_grid_path: False # default false
    old_navfn_behavior: False # default false
