DWAPlannerROS:
  max_vel_x: 0.3  #default 0.45
  min_vel_x: -0.3 # negative value means backward

 
  max_vel_y: 0.15
  min_vel_y: -0.15
  min_rot_vel: 0.1 #default 1.0
  max_rot_vel: 0.7 # not defined in default

 # min_in_place_vel_theta: 0.5 # default 0.4
   
  acc_lim_th: 0.9 # default 3.2
  acc_lim_x: 0.7 # default 2.5
  acc_lim_y: 0.7 # default 2.5

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.02
 # holonomic_robot: true

 # y_vels: '-0.6, -0.1, 0.1, 0.6'   
