recovery_behavior_enabled: true
controller_frequency: 10.0  
controller_patience: 2.0
planner_patience: 2.0 
planner_frequency: 0.2 
clearing_radius: 0.6
clearing_rotation_allowed: false
oscillation_distance: 2.0
shutdown_costmaps: false
base_global_planner: global_planner/GlobalPlanner
base_local_planner: dwa_local_planner/DWAPlannerROS
